apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snake-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: snake
  source:
    repoURL: "https://github.com/brubru-420/Argocd-SNAKE.git"
    targetRevision: main
    path: gitops/helm/snake
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: snake-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
