apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: snake-infra
  namespace: flux-system
spec:
  interval: 2m
  approvePlan: auto          # applique automatiquement (démo). Mettre "" pour valider à la main.
  path: ./gitops/infrastructure/terraform
  sourceRef:
    kind: GitRepository
    name: argocd-snake
    namespace: flux-system
  # Detection de drift : re-applique si la conf reelle diverge du .tf
  # (false = drift detection active, c'est le comportement voulu)
  disableDriftDetection: false
